#pragma once
#define _POSIX_VERSION 200809L
#define GNUSTEP_TARGET_DIR "wasm32-wasi"
#define GNUSTEP_TARGET_CPU "wasm32"
#define GNUSTEP_TARGET_OS "wasi"
#define GNUSTEP_TARGET_CONFIG_FILE "/GNUstep.conf"
#define GNUSTEP_TARGET_USER_CONFIG_FILE ".GNUstep.conf"
#define GNUSTEP_TARGET_MAKEFILES "/System/Library/Makefiles"
#define GNUSTEP_TARGET_USER_DEFAULTS_DIR "Defaults"
#define GNUSTEP_TARGET_USER_DIR_APPS "Applications"
#define GNUSTEP_TARGET_USER_DIR_ADMIN_APPS "Applications/Admin"
#define GNUSTEP_TARGET_USER_DIR_WEB_APPS "Applications/Web"
#define GNUSTEP_TARGET_USER_DIR_TOOLS "Tools"
#define GNUSTEP_TARGET_USER_DIR_ADMIN_TOOLS "Tools/Admin"
#define GNUSTEP_TARGET_USER_DIR_LIBRARY "Library"
#define GNUSTEP_TARGET_USER_DIR_LIBRARIES "Library/Libraries"
#define GNUSTEP_TARGET_USER_DIR_HEADERS "Library/Headers"
#define GNUSTEP_TARGET_USER_DIR_DOC "Library/Documentation"
#define GNUSTEP_TARGET_USER_DIR_DOC_MAN "Library/Documentation/man"
#define GNUSTEP_TARGET_USER_DIR_DOC_INFO "Library/Documentation/info"
#define GNUSTEP_TARGET_SYSTEM_USERS_DIR "/System/Users"
#define GNUSTEP_TARGET_NETWORK_USERS_DIR "/Network/Users"
#define GNUSTEP_TARGET_LOCAL_USERS_DIR "/Local/Users"
#define GNUSTEP_TARGET_SYSTEM_APPS "/System/Applications"
#define GNUSTEP_TARGET_SYSTEM_ADMIN_APPS "/System/Applications/Admin"
#define GNUSTEP_TARGET_SYSTEM_WEB_APPS "/System/Applications/Web"
#define GNUSTEP_TARGET_SYSTEM_TOOLS "/System/Tools"
#define GNUSTEP_TARGET_SYSTEM_ADMIN_TOOLS "/System/Tools/Admin"
#define GNUSTEP_TARGET_SYSTEM_LIBRARY "/System/Library"
#define GNUSTEP_TARGET_SYSTEM_LIBRARIES "/System/Library/Libraries"
#define GNUSTEP_TARGET_SYSTEM_HEADERS "/System/Library/Headers"
#define GNUSTEP_TARGET_SYSTEM_DOC "/System/Library/Documentation"
#define GNUSTEP_TARGET_SYSTEM_DOC_MAN "/System/Library/Documentation/man"
#define GNUSTEP_TARGET_SYSTEM_DOC_INFO "/System/Library/Documentation/info"
#define GNUSTEP_TARGET_NETWORK_APPS "/Network/Applications"
#define GNUSTEP_TARGET_NETWORK_ADMIN_APPS "/Network/Applications/Admin"
#define GNUSTEP_TARGET_NETWORK_WEB_APPS "/Network/Applications/Web"
#define GNUSTEP_TARGET_NETWORK_TOOLS "/Network/Tools"
#define GNUSTEP_TARGET_NETWORK_ADMIN_TOOLS "/Network/Tools/Admin"
#define GNUSTEP_TARGET_NETWORK_LIBRARY "/Network/Library"
#define GNUSTEP_TARGET_NETWORK_LIBRARIES "/Network/Library/Libraries"
#define GNUSTEP_TARGET_NETWORK_HEADERS "/Network/Library/Headers"
#define GNUSTEP_TARGET_NETWORK_DOC "/Network/Library/Documentation"
#define GNUSTEP_TARGET_NETWORK_DOC_MAN "/Network/Library/Documentation/man"
#define GNUSTEP_TARGET_NETWORK_DOC_INFO "/Network/Library/Documentation/info"
#define GNUSTEP_TARGET_LOCAL_APPS "/Local/Applications"
#define GNUSTEP_TARGET_LOCAL_ADMIN_APPS "/Local/Applications/Admin"
#define GNUSTEP_TARGET_LOCAL_WEB_APPS "/Local/Applications/Web"
#define GNUSTEP_TARGET_LOCAL_TOOLS "/Local/Tools"
#define GNUSTEP_TARGET_LOCAL_ADMIN_TOOLS "/Local/Tools/Admin"
#define GNUSTEP_TARGET_LOCAL_LIBRARY "/Local/Library"
#define GNUSTEP_TARGET_LOCAL_LIBRARIES "/Local/Library/Libraries"
#define GNUSTEP_TARGET_LOCAL_HEADERS "/Local/Library/Headers"
#define GNUSTEP_TARGET_LOCAL_DOC "/Local/Library/Documentation"
#define GNUSTEP_TARGET_LOCAL_DOC_MAN "/Local/Library/Documentation/man"
#define GNUSTEP_TARGET_LOCAL_DOC_INFO "/Local/Library/Documentation/info"
#define HAVE_DIRENT_H 1
#define HAVE_DISPATCH_DISPATCH_H 1
#define HAVE_DISPATCH_CANCEL 1
#define HAVE_FCNTL_H 1
#define HAVE_FLOAT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMORY_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UTIME_H 1
#define STDC_HEADERS 1
#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIZEOF_VOIDP 4
#define VASPRINTF_RETURNS_LENGTH 1
#define VSPRINTF_RETURNS_LENGTH 1
#define USE_LIBFFI 1
#define HAVE_FFI_PREP_CLOSURE_LOC 1

